name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
         echo Hello ${{ inputs.who-to-greet }}
         ls -lha
         cd scripts
         chmod +x *.sh
         ls -lha

      shell: bash
   # - id: random-number-generator
    #  run: echo "::set-output name=random-id::$(echo $RANDOM)"
   #   shell: bash

## echo {{ github.workspace }}
# echo "${{ github.action_path }}" >> $GITHUB_PATH
# ./scripts/good_morning.sh
