name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    #- run: echo Hello Man ${{ inputs.who-to-greet }}
     - run: ${GITHUB_ACTION_PATH//\\//}/good_morning.sh
       shell: C:\Windows\System32\bash.exe" -c "$(wslpath '%1')"
   # - id: random-number-generator
    #  run: echo "::set-output name=random-id::$(echo $RANDOM)"
   #   shell: bash
    # new version
    # echo Hello ${{ inputs.who-to-greet }}
     # echo ${{ github.action_path }}
      #ls -lha
      #cd scripts
      #chmod +x *.sh
      # ${GITHUB_ACTION_PATH//\\//}/scripts/good_morning.sh

## echo {{ github.workspace }}
# echo "${{ github.action_path }}" >> $GITHUB_PATH
# ./scripts/good_morning.sh
