name: 'Bump a dependency module'
description: 'This will bump a maven module dependency and raise a PR'
inputs:
  module_to_bump:
    description: 'Bump the module, example- name of the module'
    required: true
    default: ''
  version_to_bump:
    description: 'Version of the module to bump'
    required: true
    default: ''
  github_access_token:
    description: 'Access Token'
    required: true
    default: 'Default access token'
outputs:
  PR:
    description: "Pull Req id"
    value: "PR-123"
runs:
  using: "composite"
  steps:
    - name: Create a PR
      env:
        GITHUB_TOKEN: ${{ inputs.github_access_token }}
      shell: bash
      run: bash .${{ github.action_path }}/scripts/raise_pr.sh ${{ inputs.module_to_bump }} ${{ inputs.version_to_bump }}  ${{ inputs.github_access_token }}


