name: 'Bump a dependency module'
description: 'This will bump a maven module dependency and raise a PR'
inputs:
  module_to_bump:
    description: 'Bump the module, example- name of the module'
    required: true
    default: ''
  version_to_bump:
    description: 'Version of the module to bump'
    required: true
    default: ''
  github_access_token:
    description: 'Access Token'
    required: true
    default: 'Default access token'
outputs:
  PR:
    description: "Pull Req id"
    value: "PR-123"
runs:
  using: "composite"
  steps:
    - name: Create a PR
      env:
        GITHUB_TOKEN: ${{ inputs.github_access_token }}
      shell: bash
      run: |
        echo Input1 ${{inputs.module_to_bump}}
        echo Input1 ${{inputs.module_to_bump}}
        echo Input2 ${{inputs.version_to_bump}}
        echo Input3 ${{inputs.github_access_token}}
        git clone https://github.com/githubNinja/${{inputs.module_to_bump}}.git
        mvn versions:set -DnewVersion=${{inputs.version_to_bump}}
        git checkout -b bump-githubNinja-patch-1
        git add pom.xml
        git commit -m "chore:bump ${{inputs.module_to_bump}}"
        #git push origin bump-${{inputs.module_to_bump}}
        git push origin bump-githubNinja-patch-1
        curl  -X POST -H "Content-Type: application/vnd.github.v3+json" -H "Accept:application/vnd.github.v3+json"  -H 'Authorization: token ${{inputs.github_access_token}}' https://api.github.com/repos/githubNinja/github-actions/pulls -d '{ "title": "'Bump::github-actions::1.0.1-SNAPSHOT'", "body": "Auto Bump Pull Request.", "head": "bump-githubNinja-patch-1", "base": "main" }'
        #git pull-request -f "Bump::${{inputs.module_to_bump}}::${{version_to_bump}}" -b master
        #echo Hello ${{ inputs.who-to-greet }}
        ls
        echo executing the bash script awesome !!
        #bash ./good_morning.sh

