name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    #- run: echo Hello Man ${{ inputs.who-to-greet }}
     #- run: ${GITHUB_ACTION_PATH//\\//}/good_morning.sh
      - run: |
          echo Hello4
          echo Hello ${{ inputs.who-to-greet }}
          ls
          echo executing the bash script awesome !!
          bash ./good_morning.sh
        shell: powershell
