name: "Workflow in Linux Runner"
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  linux-runner-workflow:
    runs-on: [ linux_runner,Linux, self-hosted ]
    name: linux-runner-starter
    steps:
      - uses: actions/checkout@v2
      - id: linux-run-id1
        uses: githubNinja/github-actions@v1.0.12
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.OM_OPS_AUTOMATION_GITHUB_ACCESS_TOKEN }}
        with:
             module_to_bump: github-actions
             version_to_bump: 1.0.0-SNAPSHOT
             github_access_token: GITHUB_ACCESS_TOKEN
